# Generated by Django 4.1.6 on 2023-02-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('emp_start_date', models.DateField(auto_now_add=True)),
                ('emp_end_date', models.DateField()),
                ('photo', models.ImageField(upload_to='static/images')),
                ('status', models.CharField(choices=[('working', 'working'), ('resigned', 'resigned')], default='working', max_length=100)),
            ],
        ),
    ]
