# Generated by Django 4.1.6 on 2023-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_crud', '0002_alter_employee_emp_start_date_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='x', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='x', max_length=200),
        ),
    ]
