# Generated by Django 4.1.6 on 2023-02-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_crud', '0004_employee_age_employee_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Accounts and Finance', 'Accounts and Finance'), ('HR', 'HR'), ('Sales and marketing', 'Sales and marketing'), ('Infrastructures', 'Infrastructures'), ('Research and development', 'Research and development'), ('IT services', 'IT services'), ('Product development', 'Product development'), ('Security and transport', 'Security and transport')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
    ]
