# Generated by Django 4.1.6 on 2023-02-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_crud', '0006_alter_employee_emp_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
