# Generated by Django 4.1.6 on 2023-02-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_crud', '0007_alter_employee_emp_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exprerience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('years_of_expre', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_crud.employee')),
            ],
        ),
    ]
